---
linters-settings:
  govet:
    check-shadowing: true
  revive:
    severity: warning
  gocyclo:
    min-complexity: 42
  cyclop:
    max-complexity: 42
  dupl:
    threshold: 200
  goconst:
    min-len: 2
    min-occurrences: 3
  gci:
    local-prefixes: github.com/tbmatuka/gowebhookexec

linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - funlen
    - goconst
    - godot
    - goerr113
    - golint
    - gomnd
    - interfacer
    - lll
    - maligned
    - nestif
    - nlreturn
    - paralleltest
    - scopelint
    - whitespace
    - wrapcheck
    - wsl

run:
  skip-dirs:
    - test
  skip-files:
    - ".*_test\\.go$"
